# Generated by Django 6.1.1 on 2026-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0018_attendancesession_attendence_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
